name: nasa_app
description: Test project for Surf

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dio: ^4.0.4
  elementary: ^1.0.0

  flutter:
    sdk: flutter

  surf_lint_rules: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true