name: nasa_app
description: Test project for Surf

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dio: ^4.0.4
  elementary: ^1.0.0

  flutter:
    sdk: flutter

  golden_toolkit: ^0.13.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  mocktail: ^0.2.0
  photo_view: ^0.13.0
  surf_lint_rules: ^1.4.1
  transparent_image: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

flutter:
  generate: true

  assets:
    - assets/placeholder_image.jpeg

  uses-material-design: true